version: "3.9"

services:
  db:
    image: mysql:5.7
    volumes:
      - ./config:/docker-entrypoint-initdb.d # We need to manually define multiple databases in one container.
    restart: always
    ports:
      - "${DB_HOST_PORT}:${DB_PORT}"
    environment:
      MYSQL_ROOT_PASSWORD: local
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  first-project:
    depends_on:
      - db
    image: wordpress:latest
    extra_hosts:
      - "host.docker.internal:host-gateway" # So that Xdebug can connect with our IDE.
    ports:
      - "${FIRST_PROJECT_PORT_PRIMARY}:80"
      - "${FIRST_PROJECT_PORT_SECONDARY}:80"
    restart: always
    volumes:
      - ${FIRST_PROJECT_FOLDER}:/var/www/html
      - ./config/php.ini:/usr/local/etc/php/php.ini
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${FIRST_PROJECT_DB}
      WP_CLI_ALLOW_ROOT: "true"
    command: > # WP-CLI setup, Xdebug setup and mhsendmail setup (used for Mailhog).
      bash -c "curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar;
      chmod +x wp-cli.phar;
      mv wp-cli.phar /usr/local/bin/wp;
      pecl install xdebug;
      curl -LkSso /usr/bin/mhsendmail 'https://github.com/mailhog/mhsendmail/releases/download/v0.2.0/mhsendmail_linux_amd64';
      chmod 0755 /usr/bin/mhsendmail;
      sh /usr/local/bin/docker-entrypoint.sh;
      apache2-foreground;"

  second-project:
    depends_on:
      - db
    image: wordpress:latest
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${SECOND_PORT}:80"
    restart: always
    volumes:
      - ${SECOND_FOLDER}:/var/www/html
      - ./config/php.ini:/usr/local/etc/php/php.ini
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${SECOND_DB}
      WP_CLI_ALLOW_ROOT: "true"
    command: >
      bash -c "curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar;
      chmod +x wp-cli.phar;
      mv wp-cli.phar /usr/local/bin/wp;
      pecl install xdebug;
      curl -LkSso /usr/bin/mhsendmail 'https://github.com/mailhog/mhsendmail/releases/download/v0.2.0/mhsendmail_linux_amd64';
      chmod 0755 /usr/bin/mhsendmail;
      sh /usr/local/bin/docker-entrypoint.sh;
      apache2-foreground;"

  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none' # Don't save logs.
    ports:
      - "${MAILHOG_HOST_PORT_SMTP}:1025"
      - "${MAILHOG_HOST_PORT_WEB}:8025"
    restart: always

volumes:
  db:
    driver: local
